#if !canImport(ObjectiveC)
import XCTest

extension SemiSingletonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SemiSingletonTests = [
        ("testInvalidReentrantSemiSingletonAllocation", testInvalidReentrantSemiSingletonAllocation),
        ("testReentrantOtherClassSemiSingletonAllocation", testReentrantOtherClassSemiSingletonAllocation),
        ("testReentrantSameClassSemiSingletonAllocation", testReentrantSameClassSemiSingletonAllocation),
        ("testReentrantThroughHopSemiSingletonAllocation", testReentrantThroughHopSemiSingletonAllocation),
        ("testSimpleSemiSingletonDeallocationAsyncDispatch", testSimpleSemiSingletonDeallocationAsyncDispatch),
        ("testSimpleSemiSingletonDeallocationAutoreleasePool", testSimpleSemiSingletonDeallocationAutoreleasePool),
        ("testSimpleSemiSingletonNonReallocation", testSimpleSemiSingletonNonReallocation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SemiSingletonTests.__allTests__SemiSingletonTests),
    ]
}
#endif
